name: "adata_prepcellxgene"
description: Prepare an AnnData object for CELLxGENE visualisation by normalising embeddings and expression data
keywords:
  - single-cell
  - anndata
  - cellxgene
  - visualisation
  - scanpy
tools:
  - "scanpy":
      description: "Single-cell analysis in Python"
      homepage: "https://scanpy.readthedocs.io"
      documentation: "https://scanpy.readthedocs.io"
      tool_dev_url: "https://github.com/scverse/scanpy"
      licence:
        - "BSD-3-Clause"
      identifier: biotools:scanpy
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - h5ad:
        type: file
        description: AnnData object in h5ad format
        pattern: "*.{h5ad}"
        ontologies:
          - edam: "http://edamontology.org/format_3590"

output:
  h5ad:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.h5ad":
          type: file
          description: AnnData object prepared for CELLxGENE with log-normalised expression and reordered embeddings
          pattern: "*.h5ad"
          ontologies:
            - edam: "http://edamontology.org/format_3590"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
topics:
  versions:
    - versions.yml:
        type: string
        description: The name of the process
authors:
  - "@nictru"
maintainers:
  - "@nictru"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/python_pyyaml_scanpy:ec0559841ac88fb2
      build_id: bd-ec0559841ac88fb2_1
      scan_id: sc-f0395f3488ec7c75_1
    linux/arm64:
      name: community.wave.seqera.io/library/python_pyyaml_scanpy:7f19b28d786b0222
      build_id: bd-7f19b28d786b0222_1
      scan_id: sc-b3c44c3ae7152a6d_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pyyaml_scanpy:0177c1b99592b0c0
      build_id: bd-0177c1b99592b0c0_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/ed/ed34e104367da9d7fa40b39d78d86dce36948d95dbd2571abe923bc857bf192f/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pyyaml_scanpy:d69da01942cb3bc7
      build_id: bd-d69da01942cb3bc7_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/61/61239a82cb89944ca962bc7be4bbfc5e3761b7a708c1110881d3569fc3c6b7bb/data
  conda:
    linux/amd64:
      lock_file: modules/local/adata/prepcellxgene/.conda-lock/linux_amd64-bd-ec0559841ac88fb2_1.txt
    linux/arm64:
      lock_file: modules/local/adata/prepcellxgene/.conda-lock/linux_arm64-bd-7f19b28d786b0222_1.txt
