name: pydeseq2_differential
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.12
  - conda-forge::anndata=0.12.10
  - conda-forge::pandas=2.2.3
  - conda-forge::pyarrow=21.0.0
  - conda-forge::numpy=2.2.3
  - conda-forge::pyyaml=6.0.3
  - bioconda::pydeseq2=0.5.4
