channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-alabaster.base=1.10.0
  - bioconda::bioconductor-alabaster.se=1.10.0
  - bioconda::bioconductor-gypsum=1.6.0
  - bioconda::bioconductor-hdf5array=1.38.0
  - bioconda::bioconductor-singlecellexperiment=1.32.0
  - conda-forge::r-yaml=2.3.12
