name: adata_readrds
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::anndata2ri=2.0.1
  - bioconda::bioconductor-singlecellexperiment=1.32.0
  - conda-forge::anndata=0.13.2
  - conda-forge::pyyaml=6.0.3
  - conda-forge::r-seurat=5.5.1
