name: adata_upsetgenes
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.13.12
  - conda-forge::anndata=0.12.10
  - conda-forge::numpy=2.3.5
  - conda-forge::pyyaml=6.0.3
  - conda-forge::upsetplot=0.9.0
