name: "adata_upsetgenes"
description: Generate an UpSet plot of gene set overlaps across multiple AnnData objects
keywords:
  - single-cell
  - anndata
  - upset
  - visualisation
  - genes
tools:
  - "upsetplot":
      description: "Library for creating UpSet plots of set intersections"
      homepage: "https://upsetplot.readthedocs.io"
      documentation: "https://upsetplot.readthedocs.io"
      tool_dev_url: "https://github.com/jnothman/UpSetPlot"
      licence: ["BSD-3-Clause"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - names:
        type: string
        description: Sample names corresponding to each input AnnData object
    - h5ads:
        type: file
        description: AnnData objects in h5ad format whose gene sets are compared
        pattern: "*.{h5ad}"
        ontologies:
          - edam: "http://edamontology.org/format_3590"

output:
  plot:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.png":
          type: file
          description: UpSet plot of gene set overlaps across samples
          pattern: "*.png"
  multiqc_files:
    - "*_mqc.json":
        type: file
        description: Optional MultiQC custom content JSON for the UpSet plot
        pattern: "*_mqc.json"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750

authors:
  - "@nictru"
maintainers:
  - "@nictru"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/adata_upsetgenes:99308af0235c51d3
      build_id: bd-99308af0235c51d3_1
      scan_id: sc-fc4771afaae41695_1
    linux/arm64:
      name: community.wave.seqera.io/library/adata_upsetgenes:211d6ce081803146
      build_id: bd-211d6ce081803146_1
      scan_id: sc-b16af17d849c6021_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/adata_upsetgenes:5b6d09876e1fb7e6
      build_id: bd-5b6d09876e1fb7e6_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/37/373aa42c5a49c2b6892606e91b80eb528c90d588261e51b1272071d0e608c621/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/adata_upsetgenes:4f6412ed3e5570ab
      build_id: bd-4f6412ed3e5570ab_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/fe/fec750186498d1b2f175edb2401ad1b5da8681a7f20871147e29732c3c643531/data
  conda:
    linux/amd64:
      lock_file: modules/local/adata/upsetgenes/.conda-lock/linux_amd64-bd-99308af0235c51d3_1.txt
    linux/arm64:
      lock_file: modules/local/adata/upsetgenes/.conda-lock/linux_arm64-bd-211d6ce081803146_1.txt
