name: celltypes_cytetype
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.12
  - conda-forge::scanpy=1.10.4
  - conda-forge::pyyaml=6.0.2
  - conda-forge::threadpoolctl=3.5.0
  - pip
  - pip:
      - cytetype==0.19.3
