name: edgepython_sc_differential
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.12
  - conda-forge::anndata=0.13.2
  - conda-forge::pandas=2.3.3
  - conda-forge::numpy=2.2.3
  - conda-forge::pyyaml=6.0.3
  - conda-forge::scipy=1.15.2
  - conda-forge::matplotlib=3.10.3
  - conda-forge::adjusttext=1.4.0
  - pip
  - pip:
      - edgepython==0.2.6
