channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - anndata
  - conda-forge::pyyaml=6.0.2
  - conda-forge::pip=25.0.1
  - psutil
  - phenograph
  - pillow
  - matplotlib
  - pyparsing
  - pip:
      - doubletdetection==4.3.0.post1