name: "scanpy_neighbors"
description: Compute a k-nearest neighbours graph on a PCA or other representation
keywords:
  - neighbours
  - graph
  - single-cell
  - scanpy
tools:
  - "scanpy":
      description: "Single-cell analysis in Python"
      homepage: "https://scanpy.readthedocs.io"
      documentation: "https://scanpy.readthedocs.io"
      tool_dev_url: "https://github.com/scverse/scanpy"
      licence:
        - "BSD-3-Clause"
      identifier: biotools:scanpy
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - h5ad:
        type: file
        description: AnnData object in h5ad format with a representation in obsm
        pattern: "*.{h5ad}"
        ontologies:
          - edam: "http://edamontology.org/format_3590"
  - rep:
      type: string
      description: obsm key of the representation used to compute neighbours
  - n_pcs:
      type: integer
      description: Number of principal components to use when rep is a PCA embedding; use 0 to use all dimensions

output:
  h5ad:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.h5ad: {}
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
topics:
  versions:
    - versions.yml:
        type: string
        description: The name of the process
authors:
  - "@nictru"
maintainers:
  - "@nictru"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/python-igraph_python_pyyaml_scanpy:00dca50fd1f8bfe6
      build_id: bd-00dca50fd1f8bfe6_1
      scan_id: sc-ebd5e03fd6eb36ba_1
    linux/amd64:
      name: community.wave.seqera.io/library/python-igraph_python_pyyaml_scanpy:53120062012176bc
      build_id: bd-53120062012176bc_1
      scan_id: sc-2e5de486b4ecb8e9_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python-igraph_python_pyyaml_scanpy:b071bcea269804c4
      build_id: bd-b071bcea269804c4_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/0b/0bee94d9c751f8e4e66087403f279fc5653099009bf604cea7a8df716e424796/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python-igraph_python_pyyaml_scanpy:9c4c54f819274de5
      build_id: bd-9c4c54f819274de5_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/f3/f36c00fcbaa1da1aaa6cf25cd8a562efb6728457d4a54b46fa06395aebd2083e/data
  conda:
    linux/amd64:
      lock_file: modules/local/scanpy/neighbors/.conda-lock/linux_amd64-bd-53120062012176bc_1.txt
    linux/arm64:
      lock_file: modules/local/scanpy/neighbors/.conda-lock/linux_arm64-bd-00dca50fd1f8bfe6_1.txt
