name: "scanpy_sample"
description: Subsample cells from an AnnData object by count or fraction
keywords:
  - sampling
  - scanpy
  - single-cell
tools:
  - "scanpy":
      description: "Single-cell analysis in Python"
      homepage: "https://scanpy.readthedocs.io"
      documentation: "https://scanpy.readthedocs.io"
      tool_dev_url: "https://github.com/scverse/scanpy"
      licence: ["BSD-3-Clause"]

input:
  - - meta:
        type: map
        description: Groovy Map containing sample information
    - h5ad:
        type: file
        description: AnnData object in h5ad format
        pattern: "*.{h5ad}"
  - n:
      type: integer
      description: Absolute number of cells to sample when set
  - fraction:
      type: number
      description: Fraction of cells to sample when set

output:
  h5ad:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.h5ad":
          type: file
          description: Subsampled AnnData object
          pattern: "*.h5ad"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@nictru"
maintainers:
  - "@nictru"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/python_pyyaml_scanpy:ddf5f0922ae7dcec
      build_id: bd-ddf5f0922ae7dcec_1
      scan_id: sc-62c2fefc1f6b16eb_2
    linux/amd64:
      name: community.wave.seqera.io/library/python_pyyaml_scanpy:ab265932a4ff2ebf
      build_id: bd-ab265932a4ff2ebf_1
      scan_id: sc-60115e741406cbbf_2
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pyyaml_scanpy:3c6583657518f105
      build_id: bd-3c6583657518f105_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/bc/bc763fc46b9e3046fec418cc394fe447fd6a323f0f6f34a63b5528216eaa4f5c/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pyyaml_scanpy:d182b95b1ec879c8
      build_id: bd-d182b95b1ec879c8_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/38/386e532a346d91ce6e59118da064b9367024f807fb7a52d1e13457a0d01107f2/data
  conda:
    linux/amd64:
      lock_file: modules/local/scanpy/sample/.conda-lock/linux_amd64-bd-ab265932a4ff2ebf_1.txt
    linux/arm64:
      lock_file: modules/local/scanpy/sample/.conda-lock/linux_arm64-bd-ddf5f0922ae7dcec_1.txt
