channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-anndatar=1.0.2
  - bioconda::bioconductor-celda=1.26.0
  - bioconda::bioconductor-rhdf5=2.54.1
  - bioconda::bioconductor-singlecellexperiment=1.32.0
