channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.13.14
  - conda-forge::anndata=0.13.2
  - conda-forge::pyyaml=6.0.3
  - conda-forge::zarr=2.18.7
  - conda-forge::numcodecs=0.16.5
  - conda-forge::hnswlib=0.8.0
  - pip
  - pip:
      - scimilarity==0.4.1
