name: "scanpy_log1pnorm"
description: Log1p-transform and normalise expression counts per cell using Scanpy
keywords:
  - normalisation
  - preprocessing
  - single-cell
  - scanpy
tools:
  - "scanpy":
      description: "Single-cell analysis in Python"
      homepage: "https://scanpy.readthedocs.io"
      documentation: "https://scanpy.readthedocs.io"
      tool_dev_url: "https://github.com/scverse/scanpy"
      licence:
        - "BSD-3-Clause"
      identifier: biotools:scanpy
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - h5ad:
        type: file
        description: AnnData object in h5ad format with raw counts
        pattern: "*.{h5ad}"
        ontologies:
          - edam: "http://edamontology.org/format_3590"

output:
  h5ad:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${prefix}.h5ad: {}
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
topics:
  versions:
    - versions.yml:
        type: string
        description: The name of the process
authors:
  - "@nictru"
maintainers:
  - "@nictru"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/python_pyyaml_anndata_scanpy:78841aafc4e2a25a
      build_id: bd-78841aafc4e2a25a_1
      scan_id: sc-036935070350f78e_1
    linux/amd64:
      name: community.wave.seqera.io/library/python_pyyaml_anndata_scanpy:7df6225e45ce62d7
      build_id: bd-7df6225e45ce62d7_1
      scan_id: sc-8c5fc60a7ab7f9b6_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pyyaml_anndata_scanpy:ae892d590e8b2d23
      build_id: bd-ae892d590e8b2d23_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8e/8ee13ecdaa99dce07a579e1d2fdb44fe541679c272ca78ad23752e6884fe05b7/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pyyaml_anndata_scanpy:31c818cf3b5a8073
      build_id: bd-31c818cf3b5a8073_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/35/354081f1aea522edf9eb2503417bfd3ac227e5f6cc419192042d47a1457bfb15/data
  conda:
    linux/amd64:
      lock_file: modules/local/scanpy/log1pnorm/.conda-lock/linux_amd64-bd-7df6225e45ce62d7_1.txt
    linux/arm64:
      lock_file: modules/local/scanpy/log1pnorm/.conda-lock/linux_arm64-bd-78841aafc4e2a25a_1.txt
