channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::scvi-tools=1.4.3
  - conda-forge::scanpy=1.11.4
  - conda-forge::scipy=1.12.0
  - conda-forge::pyarrow=25.0.0
  - pip
  - pip:
      - scArches==0.6.1
